Repository 2nnerPeace/The-Moon-Ha-Android, pull requests merged in 2024-08, with the labels that each got.

#8 [BITE] [KAN-20] Before&After UI 및 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/innerpeace/themoonha/adapter/BeforeAfterAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/BeforeAfterContent.kt
  app/src/main/java/com/innerpeace/themoonha/ui/activity/beforeafter/view/BeforeAfterListFragment.kt
  app/src/main/res/drawable-v24/ic_after.png
  app/src/main/res/drawable-v24/ic_angle.png
  app/src/main/res/drawable-v24/ic_before.png
  app/src/main/res/drawable-v24/ic_zzang9.png
  app/src/main/res/layout/fragment_before_after_content.xml
  app/src/main/res/layout/fragment_before_after_list.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/styles.xml
Labels: Feat, Design

#14 [COMMON] [KAN-60] 패키지 구조 수정
  app/src/main/java/com/innerpeace/themoonha/adapter/BeforeAfterAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/beforeafter/BeforeAfterDetailFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/beforeafter/BeforeAfterListFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/craft/CraftFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/CartFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonDetailFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/live/LiveFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeHomeFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungePostFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungePostWriteFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/schedule/ScheduleFragment.kt
  app/src/main/res/navigation/navigation_graph.xml
Labels: Refactor

#24 [LOUNGE] [KAN-27] 라운지 목록 화면 구현
  app/src/main/java/com/innerpeace/themoonha/adapter/LoungeAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/LoungeListResponse.kt
  app/src/main/java/com/innerpeace/themoonha/service/LoungeService.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeViewHolder.kt
  app/src/main/java/com/innerpeace/themoonha/viewmodel/LoungeViewModel.kt
  app/src/main/res/drawable-v24/ic_new.png
  app/src/main/res/layout/fragment_lounge.xml
  app/src/main/res/layout/item_lounge.xml
Labels: Feat

#26 [LESSON] [KAN-12] 강좌 목록 조회 페이지 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/innerpeace/themoonha/adapter/LessonAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/ShortFormAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lesson/Branch.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lesson/LessonDTO.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lesson/LessonListRequest.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lesson/LessonListResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lesson/ShortFormDTO.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lesson/TargetType.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/LessonService.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/RetrofitClient.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/LessonRepository.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/LessonViewModel.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/factory/LessonViewModelFactory.kt
  app/src/main/res/color/branch_button_color.xml
  app/src/main/res/drawable-v24/branch_button_background.xml
  app/src/main/res/drawable-v24/button_border_black.xml
  app/src/main/res/drawable-v24/dialog_background.xml
  app/src/main/res/drawable-v24/ic_short_form.png
  app/src/main/res/drawable-v24/rounded_black_background.xml
  app/src/main/res/drawable-v24/rounded_green_background.xml
  app/src/main/res/drawable-v24/short_form_image_border.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/lesson_button_background.xml
  app/src/main/res/drawable/lesson_craft_button.xml
  app/src/main/res/drawable/lesson_my_culture_button.xml
  app/src/main/res/drawable/lesson_search_button.xml
  app/src/main/res/drawable/lesson_streaming__button.xml
  app/src/main/res/layout/branch_selection_dialog.xml
  app/src/main/res/layout/fragment_lesson.xml
  app/src/main/res/layout/fragment_lesson_item.xml
  app/src/main/res/layout/fragment_short_form_item.xml
  app/src/main/res/layout/test.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: Feat

#28 [LESSON] [KAN-12] Retrofit 호출 로직 수정
  app/src/main/java/com/innerpeace/themoonha/data/network/RetrofitClient.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonFragment.kt
  app/src/main/res/values/styles.xml
Labels: Feat
