Repository 2nnerPeace/The-Moon-Ha-Android, pull requests merged in 2024-09, with the labels that each got.

#30 [LESSON] [KAN-59] 금주의 1분 강좌 상세보기 구현
  app/build.gradle
  app/src/main/java/com/innerpeace/themoonha/adapter/ShortFormAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/ShortFormDetailAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lesson/ShortFormDTO.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/ShortFormDetailFragment.kt
  app/src/main/res/drawable-v24/ic_arrow_down.xml
  app/src/main/res/drawable-v24/ic_pause.png
  app/src/main/res/drawable-v24/ic_play.png
  app/src/main/res/drawable/branch_button_background.xml
  app/src/main/res/drawable/button_border_black.xml
  app/src/main/res/drawable/circle_background.xml
  app/src/main/res/drawable/dialog_background.xml
  app/src/main/res/drawable/rounded_background_light_gray_1.xml
  app/src/main/res/drawable/rounded_background_light_gray_2.xml
  app/src/main/res/drawable/rounded_black_background.xml
  app/src/main/res/drawable/rounded_border_live_main.xml
  app/src/main/res/drawable/rounded_corner_content.xml
  app/src/main/res/drawable/rounded_green_background.xml
  app/src/main/res/drawable/sample_video_thumbnail.xml
  app/src/main/res/drawable/short_form_hamburger.xml
  app/src/main/res/drawable/short_form_image_border.xml
  app/src/main/res/drawable/short_form_left_arrow.xml
  app/src/main/res/layout/fragment_short_form_detail.xml
  app/src/main/res/layout/fragment_short_form_detail_item.xml
  app/src/main/res/menu/short_form_menu.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: Feat

#33 [LESSON] [KAN-17] 강좌 상세 조회 페이지 구현
  app/build.gradle
  app/src/main/java/com/innerpeace/themoonha/adapter/LessonAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lesson/LessonDetailResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/LessonService.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/LessonRepository.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonDetailFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/LessonViewModel.kt
  app/src/main/res/drawable/basic_profile.xml
  app/src/main/res/drawable/profile_circle_background.xml
  app/src/main/res/layout/fragment_lesson_detail.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/styles.xml
Labels: Feat

#39 [CRAFT] [KAN-61] 문화공방 메인 페이지 조회 기능 구현
  app/src/main/java/com/innerpeace/themoonha/adapter/PrologueAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/PrologueThemeAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/SuggestionAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/craft/CommonResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/craft/CraftMainResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/craft/Criteria.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/craft/PageDTO.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/craft/PrologueDTO.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/craft/PrologueThemeDTO.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/craft/SuggestionDTO.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/craft/SuggestionRequest.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/craft/SuggestionResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/craft/WishLessonDTO.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/CraftService.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/CraftRepository.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/craft/CraftFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/craft/PrologueDetailFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/CraftViewModel.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/factory/CraftViewModelFactory.kt
  app/src/main/res/drawable-v24/ic_jellbbo.png
  app/src/main/res/drawable-v24/ic_next.png
  app/src/main/res/drawable-v24/ic_prev.png
  app/src/main/res/drawable/chat_bubble_background.xml
  app/src/main/res/drawable/progress_bar_green.xml
  app/src/main/res/drawable/prologue_already_liked.xml
  app/src/main/res/drawable/prologue_like.xml
  app/src/main/res/drawable/rounded_corner_content.xml
  app/src/main/res/drawable/rounded_image_background.xml
  app/src/main/res/drawable/suggestion_input_background.xml
  app/src/main/res/drawable/suggestion_input_button.xml
  app/src/main/res/drawable/wish_lesson_green_border.xml
  app/src/main/res/drawable/wish_lesson_progress.xml
  app/src/main/res/layout/fragment_craft.xml
  app/src/main/res/layout/fragment_lesson.xml
  app/src/main/res/layout/fragment_prologue_detail.xml
  app/src/main/res/layout/fragment_prologue_item.xml
  app/src/main/res/layout/fragment_prologue_theme.xml
  app/src/main/res/layout/fragment_short_form_detail.xml
  app/src/main/res/layout/fragment_suggestion_item.xml
  app/src/main/res/layout/fragment_wish_lesson_item.xml
  app/src/main/res/layout/fragment_wish_lesson_vs.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: Feat

#42 [BITE] [KAN-23] 정렬 기능 추가
  app/src/main/java/com/innerpeace/themoonha/adapter/FieldContentAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/FieldListAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/BeforeAfterService.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/FieldService.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/BeforeAfterRepository.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/FieldRepository.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/beforeafter/BeforeAfterListFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/field/FieldListFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/BeforeAfterViewModel.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/FieldViewModel.kt
  app/src/main/res/layout/fragment_before_after_list.xml
  app/src/main/res/layout/fragment_field_list.xml
Labels: Feat

#44 [LESSON] [KAN-26] 강좌 장바구니 페이지 구현
  app/build.gradle
  app/src/main/java/com/innerpeace/themoonha/adapter/CartAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/CartItemAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/LessonAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lesson/CartRequest.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lesson/CartResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lesson/LessonDetailResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lesson/SugangRequest.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/LessonService.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/LessonRepository.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/CartContentFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/CartFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonDetailFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/LessonViewModel.kt
  app/src/main/res/drawable/cart_drag_background.xml
  app/src/main/res/drawable/ic_cart_drag.xml
  app/src/main/res/drawable/ic_cart_drag_bar.xml
  app/src/main/res/drawable/lesson_detail_dialog_button_background.xml
  app/src/main/res/layout/fragment_calendar_day.xml
  app/src/main/res/layout/fragment_calendar_day_title.xml
  app/src/main/res/layout/fragment_calendar_day_title_text.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_cart_branch.xml
  app/src/main/res/layout/fragment_cart_content.xml
  app/src/main/res/layout/fragment_cart_duplicate_dialog.xml
  app/src/main/res/layout/fragment_cart_item.xml
  app/src/main/res/layout/fragment_lesson.xml
  app/src/main/res/layout/fragment_lesson_detail.xml
  app/src/main/res/layout/fragment_lesson_detail_dialog.xml
  app/src/main/res/navigation/navigation_graph.xml
  settings.gradle
Labels: Feat

#46 [CRAFT] [KAN-15] 프롤로그 상세 조회 영상 height 조절
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/CartContentFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/LessonViewModel.kt
  app/src/main/res/layout/fragment_prologue_detail.xml
Labels: Feat

#50 [LIVE] [KAN-52] fix: 충돌 해결
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/beforeafter/BeforeAfterListFragment.kt
Labels: Fix

#51 [SCHEDULE] [KAN-34] 월간 스케줄 보기 구현
  app/src/main/java/com/innerpeace/themoonha/adapter/schedule/ScheduleDialogAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/schedule/ScheduleMonthlyResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/ScheduleService.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/ScheduleRepository.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/schedule/ScheduleFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/schedule/ScheduleMonthlyFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/schedule/ScheduleWeeklyFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/ScheduleViewModel.kt
  app/src/main/res/layout/dialog_lesson_info.xml
  app/src/main/res/layout/fragment_schedule.xml
  app/src/main/res/layout/fragment_schedule_monthly.xml
  app/src/main/res/layout/fragment_schedule_weekly.xml
  app/src/main/res/layout/item_dialog_lesson_info.xml
  app/src/main/res/layout/item_next_lesson.xml
Labels: Feat

#53 [SCHEDULE] [KAN-34] 다음 스케줄 보기 구현
  app/src/main/java/com/innerpeace/themoonha/data/model/lounge/LoungeHomeResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lounge/LoungePostResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/schedule/ScheduleNextResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/ScheduleService.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/ScheduleRepository.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/schedule/ScheduleFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/schedule/ScheduleMonthlyFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/ScheduleViewModel.kt
  app/src/main/res/layout/dialog_lesson_info.xml
  app/src/main/res/layout/fragment_schedule.xml
  app/src/main/res/layout/item_next_lesson.xml
Labels: Feat

#56 [LESSON] [KAN-59] 숏폼 상세 조회 시 첫번째 데이터만 불러오던 로직 해결
  app/src/main/java/com/innerpeace/themoonha/adapter/ShortFormAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/ShortFormDetailAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/ShortFormDetailFragment.kt
Labels: Feat

#62 [COMMON] 로그인 페이지 구현 및 토큰 상태 유지
  app/build.gradle
  app/src/main/java/com/innerpeace/themoonha/SharedPreferencesManager.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/ShortFormAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/ShortFormDetailAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/auth/LoginRequest.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/ApiClient.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/AuthService.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/AuthRepository.kt
  app/src/main/java/com/innerpeace/themoonha/ui/activity/common/MainActivity.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/auth/SignInFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonDetailFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/ShortFormDetailFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/LessonViewModel.kt
  app/src/main/res/layout/fragment_lesson.xml
  app/src/main/res/layout/fragment_lesson_item.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/menu/bottom_navigation.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: Feat

#68 [LIVE] [KAN-20] 문화 한입 및 실시간 코드 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/innerpeace/themoonha/adapter/bite/BeforeAfterDetailAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/bite/FieldDetailAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/live/LiveLessonMainInfoAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/live/LiveLessonDetailResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/live/LiveLessonInfo.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/BeforeAfterService.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/FieldService.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/BeforeAfterRepository.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/FieldRepository.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/beforeafter/BeforeAfterDetailFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/beforeafter/BeforeAfterEnrollContentsFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/beforeafter/BeforeAfterEnrollContentsPhraseFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/beforeafter/BeforeAfterListFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/field/FieldDetailFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/field/FieldEnrollContentsFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/field/FieldEnrollContentsPhraseFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/field/FieldListFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/live/LiveStreamingMainFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/live/LiveStreamingMainInfoFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/BeforeAfterViewModel.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/FieldViewModel.kt
  app/src/main/res/layout/fragment_before_after_content.xml
  app/src/main/res/layout/fragment_before_after_detail.xml
  app/src/main/res/layout/fragment_before_after_detail_item.xml
  app/src/main/res/layout/fragment_before_after_enroll_contents.xml
  app/src/main/res/layout/fragment_before_after_enroll_contents_phrase.xml
  app/src/main/res/layout/fragment_before_after_list.xml
  app/src/main/res/layout/fragment_field_category.xml
  app/src/main/res/layout/fragment_field_content.xml
  app/src/main/res/layout/fragment_field_detail_item.xml
  app/src/main/res/layout/fragment_field_enroll_contents.xml
  app/src/main/res/layout/fragment_field_enroll_contents_phrase.xml
  app/src/main/res/layout/fragment_field_list.xml
  app/src/main/res/layout/fragment_live_content.xml
  app/src/main/res/layout/fragment_live_streaming_main.xml
  app/src/main/res/layout/fragment_live_streaming_main_info.xml
  app/src/main/res/layout/fragment_live_streaming_main_info_item.xml
  app/src/main/res/layout/spinner_dropdown_item.xml
  app/src/main/res/layout/spinner_selected_item.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: Fix, Refactor

#71 [BITE] [LIVE] [KAN-23] UI 및 기능 수정
  app/src/main/java/com/innerpeace/themoonha/adapter/bite/BeforeAfterDetailAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/bite/FieldDetailAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/live/LiveMyLiveLessonListAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/live/LiveOnAirListAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/ApiClient.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/beforeafter/BeforeAfterDetailFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/beforeafter/BeforeAfterEnrollContentsFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/beforeafter/BeforeAfterEnrollContentsPhraseFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/field/FieldDetailFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/field/FieldEnrollContentsFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/field/FieldEnrollContentsPhraseFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/live/LiveStreamingMainFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/live/LiveStreamingMainInfoFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/BeforeAfterViewModel.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/FieldViewModel.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/LiveViewModel.kt
  app/src/main/res/layout/fragment_before_after_content.xml
  app/src/main/res/layout/fragment_before_after_enroll_contents.xml
  app/src/main/res/layout/fragment_before_after_list.xml
  app/src/main/res/layout/fragment_field_content.xml
  app/src/main/res/layout/fragment_field_detail.xml
  app/src/main/res/layout/fragment_field_detail_item.xml
  app/src/main/res/layout/fragment_field_enroll_contents.xml
Labels: Fix, Refactor, Design

#73 [LESSON] [CRAFT] 전체적인 디자인 수정 및 기능 보완
  app/src/main/java/com/innerpeace/themoonha/adapter/CartAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/LessonDetailReviewAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/PrologueThemeAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/ShortFormDetailAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/SuggestionAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lesson/LessonReview.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/ApiClient.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/LessonService.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/LessonRepository.kt
  app/src/main/java/com/innerpeace/themoonha/ui/activity/common/MainActivity.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/craft/CraftFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/craft/PrologueSpacingItemDecoration.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/CartContentFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/CartFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonDetailFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/LessonFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/ShortFormDetailFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/LessonViewModel.kt
  app/src/main/res/drawable-v24/ic_short_form.png
  app/src/main/res/drawable/branch_button_background.xml
  app/src/main/res/drawable/chat_bubble_background.xml
  app/src/main/res/drawable/gradient_bottom.xml
  app/src/main/res/drawable/gradient_top.xml
  app/src/main/res/drawable/ic_lesson_cart.xml
  app/src/main/res/drawable/ic_short_form.xml
  app/src/main/res/drawable/rounded_black_background.xml
  app/src/main/res/drawable/rounded_dialog_background.xml
  app/src/main/res/drawable/rounded_green_background.xml
  app/src/main/res/layout/branch_selection_dialog.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_cart_branch.xml
  app/src/main/res/layout/fragment_cart_content.xml
  app/src/main/res/layout/fragment_cart_item.xml
  app/src/main/res/layout/fragment_craft.xml
  app/src/main/res/layout/fragment_lesson.xml
  app/src/main/res/layout/fragment_lesson_detail.xml
  app/src/main/res/layout/fragment_lesson_detail_dialog.xml
  app/src/main/res/layout/fragment_lesson_detail_review_item.xml
  app/src/main/res/layout/fragment_lesson_item.xml
  app/src/main/res/layout/fragment_prologue_item.xml
  app/src/main/res/layout/fragment_prologue_theme.xml
  app/src/main/res/layout/fragment_short_form_detail.xml
  app/src/main/res/layout/fragment_short_form_detail_item.xml
  app/src/main/res/layout/fragment_short_form_item.xml
  app/src/main/res/layout/fragment_suggestion_item.xml
  app/src/main/res/layout/fragment_wish_lesson_item.xml
  app/src/main/res/layout/sugang_success_alert_dialog.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: Feat, Design

#77 [LESSON] [CRAFT] 디자인 보완
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/craft/CraftFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/CartContentFragment.kt
  app/src/main/res/drawable/chat_input_box.xml
  app/src/main/res/layout/fragment_calendar_day.xml
  app/src/main/res/layout/fragment_cart_content.xml
  app/src/main/res/layout/fragment_cart_item.xml
  app/src/main/res/layout/fragment_craft.xml
  app/src/main/res/layout/fragment_lesson_detail_review_item.xml
  app/src/main/res/layout/fragment_suggestion_item.xml
  app/src/main/res/values/colors.xml
Labels: Design

#78 [LIVE] [KAN-53] 실시간 강좌 시청 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/innerpeace/themoonha/data/network/LiveService.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/LiveRepository.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/live/LiveStreamingMainFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/live/LiveStreamingMainInfoFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/LiveViewModel.kt
  app/src/main/res/drawable-v24/selector_button.xml
  app/src/main/res/layout/fragment_live_streaming_main.xml
  app/src/main/res/layout/fragment_live_streaming_main_info.xml
Labels: Fix, Feat

#80 [LESSON] 강좌 메인페이지 디자인 보완
  app/src/main/java/com/innerpeace/themoonha/data/model/craft/PrologueDTO.kt
  app/src/main/res/drawable/ic_lesson_cart.xml
  app/src/main/res/layout/fragment_cart_branch.xml
  app/src/main/res/layout/fragment_cart_item.xml
  app/src/main/res/layout/fragment_craft.xml
  app/src/main/res/layout/fragment_lesson_item.xml
  app/src/main/res/layout/fragment_short_form_item.xml
  app/src/main/res/layout/fragment_wish_lesson_item.xml
Labels: Design

#85 [CART] 강좌 제거 기능 구현
  app/src/main/java/com/innerpeace/themoonha/adapter/CartItemAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/LessonService.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/LessonRepository.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/CartContentFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/LessonViewModel.kt
  app/src/main/res/layout/fragment_cart_item.xml
Labels: Feat

#88 [SCHEDULE} [KAN-34] 주간 스케줄 날짜 오류 수정
  app/src/main/java/com/innerpeace/themoonha/adapter/schedule/ScheduleWeeklyAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/schedule/ScheduleWeeklyViewHolder.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/schedule/ScheduleWeeklyFragment.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/ScheduleViewModel.kt
  app/src/main/res/layout/item_schedule_one_week.xml
Labels: Fix

#90 [AUTH] 로그아웃 기능 추가
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/auth/SignInFragment.kt
  app/src/main/res/layout/fragment_sign_in.xml
Labels: Feat

#92 [LIVE] [BITE] 실시간 방송 ONAIR 목록 수정 및 문화 한입 디자인 개선
  app/src/main/java/com/innerpeace/themoonha/adapter/bite/BeforeAfterDetailAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/bite/FieldDetailAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/live/LiveLessonInfo.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/live/LiveLessonResponse.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/live/LiveOnAirListFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/live/LiveStreamingMainInfoFragment.kt
  app/src/main/res/layout/fragment_before_after_detail_item.xml
  app/src/main/res/layout/fragment_before_after_enroll_contents_phrase.xml
  app/src/main/res/layout/fragment_field_detail_item.xml
  app/src/main/res/layout/fragment_field_enroll_contents_phrase.xml
  app/src/main/res/layout/fragment_live_on_air_list.xml
  app/src/main/res/layout/fragment_live_streaming_main_info.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: Feat, Design

#94 [LOUNGE] [KAN-34] 주간 스케줄 날짜 오류 수정, 알림 클릭 시 프라그먼트 이동
  app/src/main/java/com/innerpeace/themoonha/adapter/schedule/ScheduleWeeklyViewHolder.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/FcmService.kt
  app/src/main/java/com/innerpeace/themoonha/ui/activity/common/MainActivity.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeHomeFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeHomeLoungeTabFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungePostWriteFragment.kt
  app/src/main/res/layout/fragment_lounge_home_info_tab.xml
  app/src/main/res/layout/fragment_schedule_weekly.xml
  app/src/main/res/layout/item_schedule_one_week.xml
  app/src/main/res/layout/item_time_table.xml
Labels: Fix, Feat

#96 [LIVE] [KAN-58] 실시간 방송 종료 화면 추가
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/live/LiveStreamingMainFragment.kt
Labels: Feat

#100 [SCHEDULE] [KAN-37] 주간 스케줄 화면 비율 수정
  app/src/main/java/com/innerpeace/themoonha/adapter/lounge/viewHolder/LoungeHomePostViewHolder.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/schedule/ScheduleWeeklyViewHolder.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/FcmService.kt
  app/src/main/java/com/innerpeace/themoonha/ui/activity/common/MainActivity.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lesson/CartContentFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeHomeFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeHomeInfoTabFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeHomeLoungeTabFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungePostFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/schedule/ScheduleWeeklyFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/util/LoadingDialog.kt
  app/src/main/res/drawable/ic_noti.png
  app/src/main/res/layout/dialog_attendance.xml
  app/src/main/res/layout/fragment_lounge_home.xml
  app/src/main/res/layout/fragment_lounge_home_info_tab.xml
  app/src/main/res/layout/fragment_lounge_home_lounge_tab.xml
  app/src/main/res/layout/fragment_lounge_post.xml
  app/src/main/res/layout/fragment_schedule_weekly.xml
  app/src/main/res/layout/item_attendance_member.xml
  app/src/main/res/layout/item_member.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: Fix

#102 [COMMON] [KAN-44] 주석 추가
  app/src/main/java/com/innerpeace/themoonha/adapter/lounge/AttendanceViewAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/lounge/LoungeHomeNoticeViewAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/lounge/LoungeHomePostViewAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/lounge/LoungeListViewAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/lounge/LoungePostImageAddAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/lounge/viewHolder/LoungeHomeMemberViewHolder.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/lounge/viewHolder/LoungeHomeNoticeViewHolder.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/lounge/viewHolder/LoungeHomePostViewHolder.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/lounge/viewHolder/LoungeListViewHolder.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/schedule/ScheduleMonthlyDialogAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/schedule/ScheduleWeeklyAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/schedule/ScheduleWeeklyDialogAdapter.kt
  app/src/main/java/com/innerpeace/themoonha/adapter/schedule/ScheduleWeeklyViewHolder.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/lounge/LoungeListResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/model/schedule/ScheduleWeeklyResponse.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/AlimService.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/LoungeService.kt
  app/src/main/java/com/innerpeace/themoonha/data/network/ScheduleService.kt
  app/src/main/java/com/innerpeace/themoonha/data/repository/LoungeRepository.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeHomeFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeHomeInfoTabFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungeHomeLoungeTabFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungePostFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/lounge/LoungePostWriteFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/schedule/ScheduleFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/schedule/ScheduleMonthlyFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/fragment/schedule/ScheduleWeeklyFragment.kt
  app/src/main/java/com/innerpeace/themoonha/ui/util/Colors.kt
  app/src/main/java/com/innerpeace/themoonha/ui/util/NewScrollView.kt
  app/src/main/java/com/innerpeace/themoonha/viewModel/ScheduleViewModel.kt
  app/src/main/res/layout/dialog_attendance.xml
Labels: Style
